Repository CigaretteAfterCoding/Amadda, pull requests merged in 2021-10, with the labels that each got.

#122 비밀번호 입력시 인풋폼으로 포커스되는 버그 수정
  client/src/components/SignInForm/SignInForm.tsx
  client/src/components/SignUpForm/SignUpForm.tsx
Labels: bugfix

#123 Release 0.0.13
  .github/workflows/main.yml
  client/src/components/DiaryModal/DiaryModal.tsx
  client/src/components/SignInForm/SignInForm.tsx
  client/src/components/SignUpForm/SignUpForm.tsx
  client/src/layouts/Header/Header.tsx
  client/src/pages/MainPage/MainPage.tsx
  package-lock.json
  server/package.json
Labels: release

#126 글쓰기 모드 중 이미지 삽입 기능 구현
  client/src/components/DiaryModal/DiaryModal.tsx
  client/src/pages/MainPage/MainPage.tsx
  server/package-lock.json
  server/package.json
Labels: client, feature

#127 storybook 셋업 및 SignUpForm 스토리 추가
  .github/workflows/main.yml
  client/.storybook/main.js
  client/.storybook/preview.js
  client/package-lock.json
  client/package.json
  client/src/components/SignInForm/SignInForm.stories.tsx
  client/src/components/SignUpForm/SignUpForm.stories.tsx
  package-lock.json
Labels: client, env

#128 Release 0.0.14
  .github/workflows/main.yml
  client/.storybook/main.js
  client/.storybook/preview.js
  client/package-lock.json
  client/package.json
  client/src/components/DiaryModal/DiaryModal.tsx
  client/src/components/SignInForm/SignInForm.stories.tsx
  client/src/components/SignUpForm/SignUpForm.stories.tsx
  client/src/pages/MainPage/MainPage.tsx
  package-lock.json
  server/package-lock.json
  server/package.json
Labels: release
